# https://github.com/rapdev-io/jon-test-open/blob/main/.github/workflows/build.yaml

name: Build new

on:
  # push:
  #   branches: [ main ]

  workflow_dispatch:

run-name: ${{ github.event.inputs.name }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  test1:
    name: test1
    if: ${{inputs.test == 'test'}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  test2:
    name: test2
    if: ${{inputs.test == 'test'}}
    needs: test1 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

  deploy:
    needs: test2
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        # run: exit 0
        run: echo Hello, world!
